.\"     Title: mate-maximus
.\"    Author: Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"      Date: 04/25/2014
.\"    Manual: User Commands
.\"    Source: MATE Desktop Environment
.\"  Language: English
.\"
.TH "MATE\-MAXIMUS" "1" "" "MATE" "User Commands"
.SH "NAME"
mate-maximus \- force all windows to be full-screen
.SH "SYNOPSIS"
mate-maximus
.SH "DESCRIPTION"
.PP
This manual page documents briefly maximus.
.PP
\fBmate-maximus\fR is an X program for the MATE Desktop Environment that forces all windows to be
full\-screen. This tool is shipped with the MATE netbook utilities.
.SH "OPTIONS"
\fBmate-maximus\fR takes no command line arguments.
.SH "AUTHOR"
This man page has been written by Mike Gabriel <mike.gabriel@das\-netzwerkteam.de> for
the Debian system and the MATE Desktop project (and it may be used by others, as well).
